services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v8.14.8
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080

  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    ports:
      - 8082:8080
    volumes:
      - ./config.yaml:/config/config.yaml:ro
      - /home/mircea/docker/gatus/data:/data
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - media-server_media-net

networks:
  media-server_media-net:
    external: true
