services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v9.0.1
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080

  gatus:
    image: twinproduction/gatus:v5.34.0
    container_name: gatus
    ports:
      - 8082:8080
    volumes:
      - ./config.yaml:/config/config.yaml:ro
      - /home/mircea/docker/gatus/data:/data
    env_file:
      - ../.env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - media-net
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "dozzle.enable=true"

networks:
  media-net:
    external: true
