---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Media Management:
    - Plex:
        icon: plex.png
        href: http://homelab:32400/web
        description: Media Server
        server: my-docker
        container: plex
        widget:
          type: plex
          url: http://homelab:32400
          key: ${PLEX_TOKEN}

    - Overseerr:
        icon: overseerr.png
        href: http://homelab:5055
        description: Media Requests
        server: my-docker
        container: overseerr
        widget:
          type: overseerr
          url: http://homelab:5055
          key: ${OVERSEERR_API_KEY}

    - Sonarr:
        icon: sonarr.png
        href: http://homelab:8989
        description: TV Series Management
        server: my-docker
        container: sonarr
        widget:
          type: sonarr
          url: http://homelab:8989
          key: ${SONARR_API_KEY}

    - Radarr:
        icon: radarr.png
        href: http://homelab:7878
        description: Movies Management
        server: my-docker
        container: radarr
        widget:
          type: radarr
          url: http://homelab:7878
          key: ${RADARR_API_KEY}

    - Prowlarr:
        icon: prowlarr.png
        href: http://homelab:9696
        description: Indexer Manager
        server: my-docker
        container: prowlarr
        widget:
          type: prowlarr
          url: http://homelab:9696
          key: ${PROWLARR_API_KEY}

    - qBittorrent:
        icon: qbittorrent.png
        href: http://homelab:8080
        description: Torrent Client
        server: my-docker
        container: qbittorrent
        widget:
          type: qbittorrent
          url: http://homelab:8080
          username: ${QBITTORRENT_USERNAME}
          password: ${QBITTORRENT_PASSWORD}

    - FlareSolverr:
        icon: flaresolverr.png
        href: http://homelab:8191
        description: Cloudflare Solver
        server: my-docker
        container: flaresolverr

- Infrastructure:
    - Portainer:
        icon: portainer.png
        href: https://homelab:9443
        description: Docker Management
        server: my-docker
        container: portainer
        widget:
          type: portainer
          url: https://homelab:9443
          env: 1
          key: ${PORTAINER_API_KEY}

    - Dozzle:
        icon: dozzle.png
        href: http://homelab:8081
        description: Docker Logs Viewer
        server: my-docker
        container: dozzle

    - Homepage:
        icon: homepage.png
        href: http://homelab:3000
        description: This Dashboard
        server: my-docker
        container: homepage

- Home Automation:
    - Home Assistant:
        icon: home-assistant.png
        href: http://homelab:8123
        description: Home Automation Platform
        server: my-docker
        container: homeassistant
        widget:
          type: homeassistant
          url: http://homelab:8123
          key: ${HOME_ASSISTANT_TOKEN}
