---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Media Management:
    - Plex:
        icon: plex.png
        href: http://homelab:32400/web
        description: Media Server
        server: my-docker
        container: plex
        showStats: true

    - Overseerr:
        icon: overseerr.png
        href: http://homelab:5055
        description: Media Requests
        server: my-docker
        container: overseerr
        showStats: true

    - Sonarr:
        icon: sonarr.png
        href: http://homelab:8989
        description: TV Series Management
        server: my-docker
        container: sonarr
        showStats: true

    - Radarr:
        icon: radarr.png
        href: http://homelab:7878
        description: Movies Management
        server: my-docker
        container: radarr
        showStats: true

    - Prowlarr:
        icon: prowlarr.png
        href: http://homelab:9696
        description: Indexer Manager
        server: my-docker
        container: prowlarr
        showStats: true

    - qBittorrent:
        icon: qbittorrent.png
        href: http://homelab:8080
        description: Torrent Client
        server: my-docker
        container: qbittorrent
        showStats: true

    - FlareSolverr:
        icon: flaresolverr.png
        href: http://homelab:8191
        description: Cloudflare Solver
        server: my-docker
        container: flaresolverr
        showStats: true

- Infrastructure:
    - Portainer:
        icon: portainer.png
        href: https://homelab:9443
        description: Docker Management
        server: my-docker
        container: portainer
        showStats: true

    - Dozzle:
        icon: dozzle.png
        href: http://homelab:8081
        description: Docker Logs Viewer
        server: my-docker
        container: dozzle
        showStats: true

    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://homelab:3001
        description: Uptime Monitoring
        server: my-docker
        container: uptime-kuma
        showStats: true

    - Homepage:
        icon: homepage.png
        href: http://homelab:3000
        description: This Dashboard
        server: my-docker
        container: homepage
        showStats: true

- Home Automation:
    - Home Assistant:
        icon: home-assistant.png
        href: http://homelab:8123
        description: Home Automation Platform
        server: my-docker
        container: homeassistant
        showStats: true
