---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: Homelab Dashboard

layout:
  # Bookmarks at the top
  Quick Links:
    style: row
    columns: 4
  # Services below
  Media Management:
    style: row
    columns: 4

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
