---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: My Awesome Homepage

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
