---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: Homelab Dashboard

layout:
  Media Management:
    style: row
    columns: 4

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
