version: "3.9"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.0.2
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/mircea/docker/qbittorrent:/config
      - external_drive:/data
    ports:
      - "8080:8080"      # WebUI
      - "6881:6881"      # BitTorrent TCP
      - "6881:6881/udp"  # BitTorrent UDP (DHT/PeX)
    restart: unless-stopped

  sonarr:
    image: ghcr.io/hotio/sonarr:release-4.0.11.2680
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/mircea/docker/sonarr:/config
      - external_drive:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: ghcr.io/hotio/radarr:release-5.14.0.9383
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/mircea/docker/radarr:/config
      - external_drive:/data
    ports:
      - "7878:7878"
    restart: unless-stopped



  prowlarr:
    image: ghcr.io/hotio/prowlarr:release-1.27.0.4852
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
      - ARGS=
    volumes:
      - /home/mircea/docker/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:develop
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - /home/mircea/docker/overseerr:/app/config
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:1.41.2
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - /home/mircea/docker/plex/config:/config
      - external_drive:/data
    restart: unless-stopped

volumes:
  external_drive:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/corsair
