tunnel: 2a32c37d-447c-4d24-9256-9deb86bc686f
credentials-file: /etc/cloudflared/2a32c37d-447c-4d24-9256-9deb86bc686f.json

ingress:
  - hostname: home-server.me
    service: http://localhost:3000
  - hostname: plex.home-server.me
    service: http://localhost:32400
  - hostname: overseerr.home-server.me
    service: http://localhost:5055
  - hostname: sonarr.home-server.me
    service: http://localhost:8989
  - hostname: radarr.home-server.me
    service: http://localhost:7878
  - hostname: prowlarr.home-server.me
    service: http://localhost:9696
  - hostname: qbittorrent.home-server.me
    service: http://localhost:8080
  - hostname: ha.home-server.me
    service: http://localhost:8123
  - hostname: dozzle.home-server.me
    service: http://localhost:8081
  - hostname: uptime.home-server.me
    service: http://localhost:3001
  - service: http_status:404
