name: Deploy Cloudflare Tunnel

on:
  push:
    branches:
      - main
    paths:
      - 'cloudflare-tunnel/compose.yml'
      - 'cloudflare-tunnel/config.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Cloudflare Tunnel
        uses: ./.github/actions/deploy-service
        with:
          service_name: Cloudflare Tunnel
          service_path: cloudflare-tunnel
          deploy_script: |
            chmod +x start.sh
            ./start.sh
          ts_authkey: ${{ secrets.TS_AUTHKEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
