name: Deploy Monitoring Stack

on:
  push:
    branches:
      - main
    paths:
      - 'monitoring/compose.yml'
      - 'monitoring/config.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy Monitoring Stack
        uses: ./.github/actions/deploy-service
        with:
          service_name: Monitoring Stack
          service_path: monitoring
          ts_authkey: ${{ secrets.TS_AUTHKEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
