name: Deploy Uptime Kuma

on:
  push:
    branches:
      - main
    paths:
      - 'uptime-kuma/compose.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Uptime Kuma
        uses: ./.github/actions/deploy-service
        with:
          service_name: Uptime Kuma
          service_path: uptime-kuma
          ts_authkey: ${{ secrets.TS_AUTHKEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
