name: Deploy Minecraft Servers

on:
  push:
    branches:
      - main
    paths:
      - 'minecraft-servers/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy Minecraft Servers
        uses: ./.github/actions/deploy-service
        with:
          service_name: Minecraft Servers
          service_path: minecraft-servers
          deploy_script: |
            docker compose -f common.compose.yml -f survival-island.compose.yml -f world-gen-server.compose.yml pull
            docker compose -f common.compose.yml -f survival-island.compose.yml -f world-gen-server.compose.yml up -d
          ts_authkey: ${{ secrets.TS_AUTHKEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
