name: Deploy Dozzle

on:
  push:
    branches:
      - main
    paths:
      - 'dozzle/compose.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy Dozzle
        uses: ./.github/actions/deploy-service
        with:
          service_name: Dozzle
          service_path: dozzle
          ts_authkey: ${{ secrets.TS_AUTHKEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
