name: Deploy Portainer

on:
  push:
    branches:
      - main
    paths:
      - 'portainer/compose.yml'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-service.yml
    with:
      service_name: Portainer
      service_path: portainer
    secrets: inherit
