name: Deploy Media Server

on:
  push:
    branches:
      - main
    paths:
      - 'media-server/compose.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Media Server
        uses: ./.github/actions/deploy-service
        with:
          service_name: Media Server
          service_path: media-server
          ts_authkey: ${{ secrets.TS_AUTHKEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
