name: Deploy Home Assistant

on:
  push:
    branches:
      - main
    paths:
      - 'home-assistant/compose.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy Home Assistant
        uses: ./.github/actions/deploy-service
        with:
          service_name: Home Assistant
          service_path: home-assistant
          ts_oauth_client_id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          ts_oauth_secret: ${{ secrets.TS_OAUTH_SECRET }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
